#
# Executes commands at the start of an interactive session.
#
# Original authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
# Modified by:
#   Sean McDaniel <sean.m.mcdaniel@gmail.com>


# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


# VARIABLES
# ---------

# See .zprofile for PATH additions.
#
# PYTHONPATH should not be set. Modify ipython startup files instead (e.g.
# ~/.ipython/profile_default/startup/00-startup.py)

# Don't add certain commands to history
HISTORY_IGNORE="(ls|ls -a|ll|ll -a|l|l -a|pwd|exit|clear|cd|cd ..|cd ../..)"

# Point 'mvim' to the current Homebrew vim
# export VIM_APP_DIR="usr/local/Cellar/macvim/HEAD-ed3fd67/" 


# SETOPTS
# -------

# Certain setopt values are set in prezto modules and don't need to be set here.

setopt AUTO_CD              # Allows 'dir' instead of 'cd dir'
setopt MULTIOS              # Pipe to multiple outputs
setopt AUTO_NAME_DIRS       # Allow for named dirs that can replace paths

setopt GLOB_COMPLETE        # Do not insert all expansion possibilities. Cycle
                            # through them like MENU_COMPLETE.

setopt AUTO_PUSHD           # CD = PUSHD
setopt PUSHD_MINUS          # Interchange +/- when used to specify a number on the stack
setopt PUSHD_TO_HOME        # Blank pushd goes to home
setopt PUSHD_IGNORE_DUPS    # Ignore multiple dirs on stack
setopt PUSHD_SILENT         # No PUSHD error messages

setopt RM_STAR_WAIT         # 10 sec wait for 'rm *' !!!
setopt IGNORE_EOF           # Do not exit on end-of-file

# KEYBINDINGS
# --------

# Common keybindings unset in python
bindkey '^A' beginning-of-line
bindkey '^E' end-of-line
bindkey '^K' kill-line
bindkey '^R' history-incremental-search-backward
bindkey '^S' history-incremental-search-forward
bindkey '^_' undo

# Incremental search using "/" and "?"
#bindkey -M vicmd "/" history-incremental-search-backward
#bindkey -M vicmd "?" history-incremental-search-forward

# VARIABLES
# ---------

# Certificate variables temporarily disabled. They were breaking 'conda'.
# (e.g. `conda update --all`)
#if [ "$HOST" =  MM241584-PC ]; then
#    # Note: Setting the CURL_CA_BUNDLE variable prevents `conda` from working.
#    export CURL_CA_BUNDLE=~/.cert/MITRE-chain.pem
#    export SSL_CERT_FILE=~/.cert/MITRE-chain.pem
#fi


# MITRE PROXY
# -----------

if [ "$HOST" =  MM241584-PC ]; then
    export http_proxy=http://gatekeeper-w.mitre.org:80/
    export HTTP_PROXY=$http_proxy

    export https_proxy=http://gatekeeper-w.mitre.org:80/
    export HTTPS_PROXY=$https_proxy

    export no_proxy=localhost,127.0.0.1,.mitre.org
    export NO_PROXY=$no_proxy

    export ALL_PROXY=$http_proxy:80
fi


# ALIASES
# -------

# Additional aliases have been defined in the prezto module (e.g. the Utility
# module). See ~/.zprezto/modules/utility/README for details.

# 'zprofile' sets a few defaults for 'ls' commands
#   -C: Mult-column output (default for terminals; therefore not included)
#   -G: colorized output
#   -F: slash after dir, asterisk after an exutible, etc.
#   -l: long format
#   -h: unit suffixes for file sizes, i.e. human readible format
alias ls='ls -GF'
alias l='ls -GF'
alias ll='ls -GFlh'


# Directory aliases (e.g. 'cd docs = cd ~/Documents/')
 
# NOTE: zprezto module 'osx' defines 'cdf' as 'cd into the current Finder
# directory'
 
hash -d docs=~/Documents/

if [[ "$HOST" = MM241584-PC ]]; then

    # Git Personal
    hash -d deorcost=~/Documents/Git\ Projects/git-personal/deorcost-rpg/
    hash -d grav=~/Documents/Git\ Projects/git-personal/ws-seanmmcdaniel-grav/
    hash -d metrics=~/Documents/Git\ Projects/git-personal/metrics/

    hash -d notes=~/Documents/Git\ Projects/git-personal/notes/
    hash -d js=~/Documents/Git\ Projects/git-personal/notes/job-search/
    hash -d pd=~/Documents/Git\ Projects/git-personal/notes/personal-development/

    hash -d py=~/Documents/Git\ Projects/git-personal/py-reference/
    hash -d rr=~/Documents/Git\ Projects/git-personal/r-reference/

    # Git Work
    hash -d git=~/Documents/Git\ Projects/
    hash -d pya=~/Documents/Git\ Projects/git-work/py-analysis-sm/
    hash -d hfc=~/Documents/Git\ Projects/git-work/hfc/

    # Projects Dirs
    hash -d proj=~/Documents/Projects/
    hash -d forecast=~/Documents/Projects/Forecasting\ \(2019-02\)/
    hash -d vba=~/Documents/Projects/VBA\ \(2019-03\)/

fi

# Mac Desktop
if [[ "$HOST" = SoniaMahwarsMBP.home ]]; then
    hash -d notes=~/Documents/github-repos/personal/notes/
    hash -d grav=~/Documents/github-repos/personal/ws-seanmmcdaniel-grav/pages/
    hash -d deorcost=~/Documents/github-repos/personal/deorcost-rpg/
    hash -d metrics=~/Documents/github-repos/personal/metrics/
fi


# Git aliases

# Aliases provided by the prezto git module have been disabled (see
# ~/.zpreztorc). A narrow selection of them have been manually included below
# (trying to prevent command pollution). See ~/.zprezto/modules/git/alias.zsh
# for reference. Will add more as necessary.

# Branch (b)
alias gb='git branch'

# Commit (c)
alias gcm='git commit --message'    # git commit message
alias gco='git checkout'

# Fetch (f)
alias gf='git fetch'
alias gfm='git pull'                # Pull = fetch + merge

# Index (i)
alias gia='git add'                 # git index add

# Push (p)
alias gp='git push'

# Working copy (w)
alias gwd='git diff'                # git working-directory diff
# git working-directory status
alias gws='git status --ignore-submodules=${_git_status_ignore_submodules}' 


# Misc. aliases
 
# Executable script 'mvim' launches application MacVim. It must be installed
# for the below aliases to work. (expected directory: '/usr/local/bin').
# Instruction are included as part of the standard MacVim download.
# alias vim='mvim'
alias gvim='mvim'

alias brun='brew services run'
alias bstart='brew services start'
alias bstop='brew services stop'
alias bstatus='brew services list'



# FUNCTIONS
# ---------

# ZSH modifiers are used
#   - t: pathname tail, i.e. basename
#   - r: remove filename extension
#   - e: the suffix (file extension)


# PANDOC FUNCTIONS
# 
#   1. md2docx:  Convert Markdown -> Word
#   2. md2html:  Convert Markdown -> HTML
#   3. md2html2: Convert Markdown -> HTML. HTML files go in seperate folder.
#   3. md2pdf:   Convert Markdown -> PDF
#
# The following PANDOC flags are in the various functions
#
#   - s / --standalone
#       Produce output with an appropriate header and footer
#   --toc
#       Generate a table of contents
#   --css "path/to/stylesheet.css"
#       Use CSS stylesheet 'stylesheet.css' to format HTML documents
#   --katex
#       Fast math typesetting engine for HTML (see https://github.com/Khan/KaTeX)
#   --filter pandoc-citeproc
#       Add citation and bibliography support. Requires installation of
#       'pandoc-citeproc' (homebrew)
#   --filter pandoc-crossref
#       Add figure, equation, and table cross-reference functionality. Requires
#       installation of 'pandoc-crossref' (homebrew)
#   --highlight-style kate
#       Use the HTML code formatting highlight style 'kate'


# Markdown -> Word
function md2docx {
    if test ${1:e}=="md"; then
        echo "Executing: 'pandoc -s ${1:t} -o ${1:t:r}.docx'"
        pandoc -s ${1} -o ${1:r}.docx
    else
        echo "FAILURE: Markdown file with extension *.md required"
    fi
}

# Markdown -> HTML
function md2html {
    echo "Pandoc: Creating '${1:t:r}.html' from '${1:t}'"
    pandoc -s --toc --katex \
        --filter pandoc-crossref \
        --filter pandoc-citeproc \
        --highlight-style kate \
        --css ~/.css/pandoc.css \
        -o ${1:r}.html ${1} 
}

# Markdown -> HTML
# Place the output HTML document in a seperate `html/` folder. This folder is
# assumed to exist.
function md2html2 {
    echo "Pandoc: Creating 'html/${1:t:r}.html' from '${1:t}'"
    pandoc -s --toc --katex \
        --filter pandoc-crossref \
        --filter pandoc-citeproc \
        --highlight-style kate \
        --css ~/.css/pandoc.css \
        -o html/${1:r}.html ${1} 
}

# Markdown -> PDF
function md2pdf {
    echo "Pandoc: Creating '${1:t:r}.pdf' from '${1:t}'"
    pandoc ~/.pandoc/templates/latex_template.yaml \
        --filter pandoc-crossref \
        --filter pandoc-citeproc \
        -o ${1:r}.pdf ${1} 
}


# PYTHON FUNCTIONS

# Update all homebrew (/usr/local) python packages
function p3update {
    echo "Updating Python 3x packages"
    pip3 freeze - local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U
    echo "Process complete"
}

# Set the Anaconda environment via a function
# #
# This is done manually instead of automatically so that the conda installation
# binaries don't conflict with installation of other applications (e.g. certain
# R packages).
function setcondaenv {

if [[ "$HOST" = SoniaMahwarsMBP.home ]]; then
export PATH="/Users/seanmcdaniel/anaconda/bin:$PATH"
fi

if [[ "$HOST" = MM241584-PC ]]; then
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/smcdaniel/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/smcdaniel/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/smcdaniel/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/smcdaniel/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
fi
}
